/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package touched.agi.java.app;


import touched.agi.java.app.server.Server;

public class App {

    public static void main(String[] args)  {
        Server server;
        server = new Server(5000);
        server.Startup();
    }
}
